apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-03T08:55:49Z"
  labels:
    appName: apollo
    workloadKind: Deployment
    workloadName: apollo-admin
  name: apollo-admin
  namespace: apollo
spec:
  clusterIP: 10.96.178.0
  externalTrafficPolicy: Cluster
  ports:
    - name: "8090"
      nodePort: 32108
      port: 32108
      protocol: TCP
      targetPort: 8090
  selector:
    name: apollo-admin
  sessionAffinity: None
  type: NodePort