apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-03T08:55:49Z"
  generation: 1
  labels:
    appName: apollo
  name: apollo-portal
  namespace: apollo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: apollo-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apollo
        ccse_app_name: apollo
        name: apollo-portal
        source: CCSE
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://IP:3306/ApolloPortalDB?characterEncoding=utf8   #数据库地址
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: 123456   #数据库密码
            - name: APOLLO_PORTAL_ENVS
              value: dev
            - name: DEV_META
              value: http://10.96.69.115:32109   #apollo-config的Service Ip+NodePort端口
          image: apolloconfig/apollo-portal:latest
          imagePullPolicy: Always
          name: apollo-portal
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: apollo
      nodeSelector:
        apollo: "151"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime