version: "3.7"
services:
  apollo-configservice:
    container_name: apollo-configservice
    image: apolloconfig/apollo-configservice:2.1.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    volumes:
      - /tmp/logs:/opt/logs
    healthcheck:
      test: ["CMD", "curl" ,"localhost:8080/health"]
      interval: 5s
      timeout: 1s
      retries: 10
    network_mode: "host"

  apollo-adminservice:
    container_name: apollo-adminservice
    image: apolloconfig/apollo-adminservice:2.1.0
    ports:
      - "8090:8090"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    volumes:
      - /tmp/logs:/opt/logs
    healthcheck:
      test: ["CMD", "curl" ,"localhost:8090/health"]
      interval: 5s
      timeout: 1s
      retries: 10
    depends_on:
      - apollo-configservice
    network_mode: "host"

  apollo-portal:
    container_name: apollo-portal
    image: apolloconfig/apollo-portal:2.1.0
    ports:
      - "8070:8070"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - APOLLO_PORTAL_ENVS=dev    #注意这里，如果要修改不同环境名，则数据库也必须修改 ApolloPortalDB.ServerConfig 中 apollo.portal.envs 该行的信息，否则启动会发生报错
      - PRO_META=http://localhost:8080 # 这里需要写环境名对应的 configservice 服务。
    volumes:
      - /tmp/logs:/opt/logs
    healthcheck:
      test: ["CMD", "curl" ,"localhost:8070/health"]
      interval: 5s
      timeout: 1s
      retries: 10
    depends_on:
      - apollo-adminservice
      - apollo-configservice
    network_mode: "host"