server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.85.111:3306/sakila?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    cn.daycode.fatalism.account: debug
    org.springframework: warn

sms:
  enable: true
  url: localhost:test