server:
  port: 53030
app:
  id: account-service
apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-ribbon,micro_service.spring-boot-redis,micro_service.mybatis-plus,micro_service.spring-rocketmq,micro_service.spring-cloud-hmily
spring:
  application:
    name: account-service

logging:
  level:
    root: info
    cn.daycode.fatalism.account: trace