logging:
  level:
    com.demo: debug
    org.springframework: warn

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daybreak-code/config-server.git
          username: 3358115621@qq.com
          password: test